### ISSUE TITLE
怎样使用自建节点转换工具，避免安全问题

### ISSUE THREAD

**Issue by 3377** [cmliu/CF-Workers-SUB#20]

**Comment by cmliu** [comment]
变量SUBAPI填自己的后端域名

**Comment by 3377** [comment]
支持不良林的那个转换吗，还是sublink 还是subsrore.给点标准答案呗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CMLiussss ***@***.***&gt;
发送时间: 2024年6月17日 23:59
收件人: cmliu/CF-Workers-SUB ***@***.***&gt;
抄送: 3377 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [cmliu/CF-Workers-SUB] 怎样使用自建节点转换工具，避免安全问题 (Issue #20)





 
变量SUBAPI填自己的后端域名

**Comment by cmliu** [comment]
subconverter

**Comment by cmliu** [comment]
视频教程已经在计划之中，关注我油管频道就可以了
