### ISSUE TITLE
大佬，为啥机场订阅链接中带有/api/这个字节都不能读取呀

### ISSUE THREAD

**Issue by rting738** [cmliu/CF-Workers-SUB#6]
所有带/api/和token=的机场订阅都无法读取呀，大佬有办法解决么？感谢

**Comment by cmliu** [comment]
更新了订阅后的b64解码方式, 再更新一下代码再试试还有问题吗

**Comment by rting738** [comment]
感谢，已经没问题了，可以用了，只是按照不良林自建的订阅转换使用品云的MATE后端依然转换HY2节点不成功。

**Comment by rting738** [comment]
> 更新了订阅后的b64解码方式，再更新一下代码再尝试还有问题吗？
测试多次，HY2节点还是无法解析出来，大佬有空的话是否可以解决下呢？感谢!!
