### ISSUE TITLE
无法在clashmeta的安卓版上使用

### ISSUE THREAD

**Issue by SHctt** [cmliu/CF-Workers-SUB#66]
订阅出来的节点，如果结尾加上'?format=clash'，然后把订阅地址复制到浏览器，不能直接显示配置信息，而是启动下载一个没有后缀的clash配置文件。

不知道这样算不算是一个bug。

因为安卓版的clashmeta，要么只支持下载到'.yml'格式的文件，要么就是可以直接读取配置信息的页面。

比如，使用pages搭建好了edgetunel以后，页面上输出的带'?clash'字样的订阅链接就使用得很好。

当然也有可能我使用pages搭建的workers有问题？还是说这个订阅器和博主的VLESS.fxxk.dedyn.io这个订阅器代码有差异么？

同样的问题在'WorkerVless2sub'这个库，创建的pages的workers结尾加'?clash'也是跟这里一样的症状。

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the code to handle Clash configuration requests properly, allowing direct display in the browser and adding a .yml extension for downloads.

You can review changes in this commit: https://github.com/kkpo4553/cmliu-CF-Workers-SUB-66/commit/d8a069ea3164a369cefed3b6512d634c2aa95d69.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by SHctt** [comment]
另外，edgetunel配合VLESS.fxxk.dedyn.io订阅器以后，会订阅出很多无效的ss节点，如下：
- {name: 🇯🇵 JP 5, server: 13.113.17.246, port: 443, type: ss, cipher: aes-256-cfb, password: amazonskr05}
  - {name: 🇯🇵 JP 6, server: 13.114.67.166, port: 443, type: ss, cipher: aes-256-cfb, password: amazonskr05}
  - {name: 🇯🇵 JP 7, server: 13.115.255.151, port: 443, type: ss, cipher: aes-256-cfb, password: amazonskr05}
。。。

很多很多这种无效的节点。应该也算是一个小小的bug了。

再次感谢博主的分享，也祝博主一帆风顺发大财。加油，共勉

**Comment by SHctt** [comment]
找到问题所在了，首先将代码更新到博主的最新版的代码后，在代码的200行附近，把这里发送给浏览器的头部信息改一下就可以了；
`"Content-Disposition": `attachment; filename*=utf-8''${encodeURIComponent(FileName)}; filename=${FileName}`,`
attachment改成inline，这样配置信息会直接显示在网页上。

**Comment by SHctt** [comment]
找到问题所在了，首先将代码更新到博主的最新版的代码后，在代码的200行附近，把这里发送给浏览器的头部信息改一下就可以了；
"Content-Disposition": attachment; filename*=utf-8''${encodeURIComponent(FileName)}; filename=${FileName},
attachment改成inline，这样配置信息会直接显示在网页上。

**Comment by SHctt** [comment]
另外，用正则，去修改配置文件的后缀，容易出EOF错误，有点麻烦。当然，目前的问题只出现在clashmeta的安卓版上。其他软件没有试过，不过该说一句，感觉适配安卓版的clash，而且还要支持vless的，其实也不太多。
