### ISSUE TITLE
80端口节点在clash导出后，被改变

### ISSUE THREAD

**Issue by 4228tedbear** [cmliu/CF-Workers-SUB#9]
你好，我worker vless的80端口的no TLS 节点放入订阅，在clash导出以后，节点的header-host由xxxx.worker.dev，自动变成我在worker vless绑定的域名，导致节点失效。但是在v2rayN和小火箭上没问题。请问这是什么原因呢？

**Comment by cmliu** [comment]
你是不是把edt的订阅地址和订阅器的订阅地址搞混了

**Comment by 4228tedbear** [comment]
> 你是不是把edt的订阅地址和订阅器的订阅地址搞混了

没有。就是这个汇聚订阅的项目。在v2rayN导出链接，放到汇聚订阅的worker里面，在clash订阅后就变了。
